# Generated by Django 4.2.4 on 2023-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hotel/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
